[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["wnstatmech"]
exclude = ["tutorial*"]

[project]
name = "wnstatmech"
version = "1.0.0"
dependencies = ["scipy", "numpy", "gslconsts"]
requires-python = ">=3.0"
authors = [
  {name = "Bradley S. Meyer", email = "mbradle@g.clemson.edu"},
  {name = "Lucas S. Walls", email = "lwalls@g.clemson.edu"},
]
maintainers = [
  {name = "Bradley S. Meyer", email = "mbradle@g.clemson.edu"},
]
description = "Package for handling the statistical mechanics of fermions and bosons"
readme = "README.rst"
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E.*"]
keywords = ["astronomy, nuclear astrophysics"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Programming Language :: Python :: 3"
]

[project.optional-dependencies]

[project.urls]
Documentation = "https://wnstatmech.readthedocs.org"
Repository = "https://github.com/mbradle/wnstatmech.git"
"Bug Tracker" = "https://github.com/mbradle/wnstatmech/issues"

[project.scripts]

[project.gui-scripts]

[project.entry-points."spam.magical"]
